FROM rabbitmq:4-management-alpine

ENV RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
ENV RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
ENV RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST:-/}

EXPOSE 5672 15672
